import type { RestaurantDataSchema } from "@/schema/restaurant";
import type z from "zod";

// Updated mock data based on the provided schema
export const mockDestinations = [
  {
    id: "1",
    name: "Chocolate Hills",
    description:
      "Famous geological formation with over 1,200 cone-shaped hills",
    address: "Carmen, Bohol, Philippines",
    email: null,
    phone: null,
    website: null,
    facebook: null,
    imageUrl_1:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80",
    imageUrl_2: null,
    imageUrl_3: null,
    imageUrl_4: null,
    imageUrl_5: null,
    videoUrl: null,
    latitude: null,
    longitude: null,
    count: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "2",
    name: "Tarsier Sanctuary",
    description: "Home to the world's smallest primates - Philippine Tarsiers",
    address: "Corella, Bohol, Philippines",
    email: null,
    phone: null,
    website: null,
    facebook: null,
    imageUrl_1:
      "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&q=80",
    imageUrl_2: null,
    imageUrl_3: null,
    imageUrl_4: null,
    imageUrl_5: null,
    videoUrl: null,
    latitude: null,
    longitude: null,
    count: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "3",
    name: "Baclayon Church",
    description: "Historic stone church built by Spanish missionaries in 1595",
    address: "Baclayon, Bohol, Philippines",
    email: null,
    phone: null,
    website: null,
    facebook: null,
    imageUrl_1:
      "https://images.unsplash.com/photo-1580757468214-c73f7062a5cb?w=800&q=80",
    imageUrl_2: null,
    imageUrl_3: null,
    imageUrl_4: null,
    imageUrl_5: null,
    videoUrl: null,
    latitude: null,
    longitude: null,
    count: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "4",
    name: "Loboc River",
    description: "Scenic river cruise with floating restaurant experience",
    address: "Loboc, Bohol, Philippines",
    email: null,
    phone: null,
    website: null,
    facebook: null,
    imageUrl_1:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    imageUrl_2: null,
    imageUrl_3: null,
    imageUrl_4: null,
    imageUrl_5: null,
    videoUrl: null,
    latitude: null,
    longitude: null,
    count: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "5",
    name: "Mag-Aso Falls",
    description: "Hidden waterfall perfect for swimming and nature photography",
    address: "Antequera, Bohol, Philippines",
    email: null,
    phone: null,
    website: null,
    facebook: null,
    imageUrl_1:
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    imageUrl_2: null,
    imageUrl_3: null,
    imageUrl_4: null,
    imageUrl_5: null,
    videoUrl: null,
    latitude: null,
    longitude: null,
    count: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "6",
    name: "Blood Compact Site",
    description:
      "Historical monument commemorating the first treaty of friendship",
    address: "Tagbilaran, Bohol, Philippines",
    email: null,
    phone: null,
    website: null,
    facebook: null,
    imageUrl_1:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    imageUrl_2: null,
    imageUrl_3: null,
    imageUrl_4: null,
    imageUrl_5: null,
    videoUrl: null,
    latitude: null,
    longitude: null,
    count: null,
    createdAt: null,
    updatedAt: null,
  },
];

// Sample restaurant data for Tubigon
export const restaurants: z.infer<typeof RestaurantDataSchema>[] = [
  {
    id: "1",
    name: "Seaside Grill & Bar",
    description:
      "Fresh seafood with stunning ocean views. Specializing in local catch and traditional Filipino dishes.",
    address: "Barangay Poblacion, Tubigon",
    email: "info@seasidegrill.com",
    phone: "+63 38 515 1234",
    website: "https://seasidegrill.com",
    facebook: "https://facebook.com/seasidegrill",
    imageUrl_1:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop",
    imageUrl_2:
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=600&fit=crop",
    imageUrl_3: null,
    latitude: null,
    longitude: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "2",
    name: "Tubigon Heritage Café",
    description:
      "Cozy café serving local coffee and traditional pastries in a heritage building.",
    address: "Town Center, Tubigon",
    email: "contact@heritagecafe.com",
    phone: "+63 38 515 5678",
    website: "https://heritagecafe.com",
    facebook: "https://facebook.com/heritagecafe",
    imageUrl_1:
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=600&fit=crop",
    imageUrl_2: null,
    imageUrl_3: null,
    latitude: null,
    longitude: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "3",
    name: "Mangrove View Restaurant",
    description:
      "Authentic Filipino cuisine with panoramic mangrove views. Family-owned since 1985.",
    address: "Mangrove Area, Tubigon",
    email: "mangrove@restaurant.com",
    phone: "+63 38 515 9012",
    website: null,
    facebook: "https://facebook.com/mangroverestaurant",
    imageUrl_1:
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop",
    imageUrl_2: null,
    imageUrl_3: null,
    latitude: null,
    longitude: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "4",
    name: "Island Breeze Bistro",
    description:
      "Modern bistro offering international cuisine with local ingredients and creative presentations.",
    address: "Marina District, Tubigon",
    email: "bistro@islandbreeze.com",
    phone: "+63 38 515 3456",
    website: "https://islandbreeze.com",
    facebook: null,
    imageUrl_1:
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&h=600&fit=crop",
    imageUrl_2: null,
    imageUrl_3: null,
    latitude: null,
    longitude: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "5",
    name: "Lola's Kitchen",
    description:
      "Home-style Filipino cooking passed down through generations. Known for authentic flavors.",
    address: "Barangay San Vicente, Tubigon",
    email: "lola@kitchen.com",
    phone: "+63 38 515 7890",
    website: null,
    facebook: "https://facebook.com/lolaskitchen",
    imageUrl_1:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop",
    imageUrl_2: null,
    imageUrl_3: null,
    latitude: null,
    longitude: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "6",
    name: "Coconut Grove Resto",
    description:
      "Tropical dining experience surrounded by coconut palms. Fresh seafood and tropical drinks.",
    address: "Coastal Road, Tubigon",
    email: null,
    phone: "+63 38 515 2468",
    website: "https://coconutgrove.com",
    facebook: "https://facebook.com/coconutgrove",
    imageUrl_1:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&h=600&fit=crop",
    imageUrl_2: null,
    imageUrl_3: null,
    latitude: null,
    longitude: null,
    createdAt: null,
    updatedAt: null,
  },
];
